# Configure a course calendar
# Used for title of web page
courseTitle = "Latin 101, section 2, F'22"
# YYYY-MM-DD
firstDay = "2022-08-31"
lastDay = "2022-12-17"

# Pattern of class meetings: "mwf", "tt" or "wf"
schedule = "mwf"

# Number of weeks the calendar should run for
totalWeeks =  14

fixedDates = [
  ["2022-08-29", "Advising: no classes."],
  ["2022-10-07",  "Last class before fall break."],
  ["2022-10-17",  "Classes resume."],
  ["2022-11-22",  "Last class before Thanksgiving break."],
  ["2022-11-28",  "Classes resume."],
  ["2022-12-09",  "Last day of classes."],
  ["2022-12-10",  "Study period begins."],
  ["2022-12-13",  "Final examinations begin."],
  


  ["2022-09-30",  "ğŸ“œ Mastering [unit 1 forms](../assignments/unit1/mastery/) due."],
  ["2022-10-03",  "ğŸ“œ [Reading](../assignments/unit1/reading/)  assignment 1 due."],
  ["2022-10-07",  "ğŸ“œ [Composition](../assignments/unit1/composition/)  1 due."],


  ["2022-11-04",  "ğŸ“œ Mastering [unit 2 forms](../assignments/unit2/composition/) due."],
  ["2022-11-07",  "ğŸ“œ [Reading](../assignments/unit2/reading/) assignment 2 due."],
  ["2022-11-09",  "ğŸ“œ [Composition](../assignments/unit2/composition/) 2 due."],


  ["2022-11-18",  "ğŸ“œ Mastering unit 3 forms due."],
  ["2022-11-21",  "ğŸ“œ Reading assignment 3 due."],
  ["2022-12-02",  "ğŸ“œ Composition 3 due."],





  ["2022-10-24",  "âš ï¸ **Last day to submit revisions of unit 1 assignments**."],
  ["2022-12-05",  "âš ï¸ **Last day to submit revisions of unit 2 assignments**."],


    ["2022-12-12",  "âš ï¸ **Last day to submit revisions of unit 3 assignments**"]

]




